mindmap
  root)300-096(
    ::right:: tsmc
      https
      www
      com
      nyse
      tsm
    ::left:: esg
      aebec
      jasm
      esmc
      tsr
      nyse
    ::right:: com
      https
      www
      tsmc
      nyse
      tsm
    ::left:: ai
      hpc
      cowos
      ic
      integrated
      fan-out
    ::right:: https
      www
      tsmc
      com
      nyse
      tsm
    ::left:: jasm
      tsmc
      ai
      units
      japan
      advanced
    ::right:: japan
      jasm
      tsmc
      ai
      units
      advanced
    ::left:: management
      group
      loughborough
      institute
      nasdaq
      systems