mindmap
  root)DeepSeek-R1(
    ::right:: deepseek-r
      reasoning
      zero
      pass
      rl
      performance
    ::left:: model
      reinforcement
      learning
      deepseek-r
      evaluation
      contributions
    ::right:: reasoning
      deepseek-r
      zero
      pass
      rl
      performance
    ::left:: rl
      deepseek-r
      reasoning
      zero
      pass
      performance
    ::right:: models
      reasoning
      et
      al
      rl
      deepseek-r
    ::left:: zero
      deepseek-r
      reasoning
      pass
      rl
      performance
    ::right:: performance
      deepseek-r
      reasoning
      zero
      pass
      rl
    ::left:: training
      model
      process
      zero
      reward
      answer