services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 8000
    volumes:
      - ./storage:/app/storage
    ports:
      - "8000:8000"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://backend:8000
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - backend
